# Generated by Django 5.1.2 on 2024-11-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_location_route_routestop_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='estimated_arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
